[package]
name = "mkjson"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8.6"
unicode-ident = "1.0.18"

[dev-dependencies]
assert_matches = "1"
